include: package:very_good_analysis/analysis_options.3.0.1.yaml
analyzer:
  exclude:
    - build/**
linter:
  rules:
    file_names: false
    public_member_api_docs: false
    one_member_abstracts: false
    avoid_dynamic_calls: false
    non_constant_identifier_names: false
   
