name: hallo
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  dart_frog: ^0.1.0
  dart_jsonwebtoken: ^2.4.2
  equatable: ^2.0.5
  mysql1: ^0.20.0
  postgres: ^2.5.2

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
